### ISSUE TITLE
New sign requests - Invalid sign errors

### ISSUE THREAD

**Issue by andreasbotsikas** [TuyaAPI/openapi#14]
I get an invalid sign error. Reading the docs https://developer.tuya.com/en/docs/iot/singnature?id=Ka43a5mtx1gsc#title-3-stringToSign%20signature%20string it seems that they changed the request signing process to include a payload string which we need to sign.

Is there a reason why this project doesn't use @tuya/tuya-connector-nodejs that is used in the https://github.com/TuyaAPI/link project?

**Comment by codetheweb** [comment]
This repo is outdated at this point. I'll add a note and archive it.
