### ISSUE TITLE
Inconsistency in typings

### ISSUE THREAD

**Issue by milo526** [TuyaAPI/openapi#5]
The [`getDeviceToken` method of this library](https://github.com/TuyaAPI/openapi/blob/master/src/api.ts#L152) has a return type of `Promise<string>`

While after [link library fetches it](https://github.com/TuyaAPI/link/blob/master/index.js#L85) it is [treated as an object](https://github.com/TuyaAPI/link/blob/master/index.js#L89).

Logically it can't be both 😛

**Comment by milo526** [comment]
To the best of my knowledge and testing, the provided value is indeed an object.

I propose a change in the typings of the openapi library with extra validation to ensure that the return type is indeed an object.
We could even chose to validate that all the properties are indeed present.

**Comment by codetheweb** [comment]
You're correct.

I don't think validation is necessary, but an update that changes all those Object typings to proper interfaces would be appreciated as well. Guess I was just lazy when I was originally making this since downstream consumers weren't using Typescript. 😛
