### ISSUE TITLE
Bug: not processing response correctly

### ISSUE THREAD

**Issue by codetheweb** [TuyaAPI/openapi#7]
@milo526 sorry, I should have looked at #6 more closely.

Why did you change this line? https://github.com/TuyaAPI/openapi/pull/6/files#diff-769911c416ccf8514d8fd941ae0abe8fb5c606ade0c218e22151a5f5f9f3d700L83

Seems to be causing issues now since the response body isn't being hoisted: https://github.com/codetheweb/tuyapi/issues/411.

Confirmed that a test script worked with v1.2.1 but not v1.2.2.

**Comment by milo526** [comment]
Sorry for that, that change was completely unintentional.

**Comment by codetheweb** [comment]
Ok, thanks for the quick response.

**Comment by codetheweb** [comment]
Resolved in v1.2.3.
